# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#featured'
    weight: 30
  - name: Posts
    url: '#posts'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 45
  - name: "Media"
    url: "#media"
    weight: 60
  - name: "Bio"
    url: "#mybio"
    weight: 65
  - name: "Tech Stack"
    url: "/techsetup/"
    weight: 70
  - name: "Disclosures"
    url: "/disclosures/"
    weight: 75
  - name: Contact
    url: '#contact'
    weight: 80
  - name: "CV"
    url: "pdf/CV/CV.pdf"
    weight: 90
