# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Posts
    url: '#posts'
    weight: 40
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Publications
    url: '#featured'
    weight: 50
  - name: "Media"
    url: "#media"
    weight: = 55
  - name: "Twitter"
    url: "#top_tweets"
    weight: 60
  - name: "Tech Stack"
    url: "/techsetup/"
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
  - name: "CV"
    url: "uploads/CV/CV.pdf"
    weight: 90
